
stages:
#  - test
  - deploy
  - add_version



#
#unit_test:
#  image: node:latest
#
#  stage: test
#  script:
#    - npm install
##    - npm test
#  artifacts:
#    paths:
#      - node_modules/

#Deploy for releasing to production
deploy_staging:
  stage: deploy
  tags:
    - runner2
  environment:
    name: staging
    url: https://stag.lingojingo.com
  only:
    - master
  before_script:
    - docker info
  script:
    - docker stop $(docker ps -a -q) || true
    - docker rm $(docker ps -a -q)  || true
    - docker rmi $(docker images -a -q) || true
    - docker build -t my-docker-image .
    - docker run -t -d -p 8080:8080  -e NODE_ENV=$STAG_ENV -e ES_HOST=$STAG_ES_HOST -e XTAG_TIME=$XTAG_TIME -e MONGO_STAG_URL=$MONGO_STAG_URL my-docker-image
deploy_production:
  stage: deploy
  tags:
    - runner1
  environment:
    name: production
    url: https://app.lingojingo.com
  variables:
    NODE_ENV: $PROD_ENV
    MONGO_PROD_URL: $MONGO_PROD_URL

  only:
    - /^v\d+\.\d+\.\d+$/
  before_script:
    - docker info
  script:
    - docker stop $(docker ps -a -q) || true
    - docker rm $(docker ps -a -q)  || true
    - docker rmi $(docker images -a -q) || true
    - docker build -t my-docker-image .
    - docker run -t -d -p 8080:8080  -e NODE_ENV=$PROD_ENV -e ES_HOST=$PROD_ES_HOST -e XTAG_TIME=$XTAG_TIME  -e MONGO_PROD_URL=$MONGO_PROD_URL -e PROD_FIRE_BASE_CONFIG_SERVICE=$PROD_FIRE_BASE_CONFIG_SERVICE my-docker-image

add_version_stag:
  stage: add_version
  only:
    - /^r\d+\.\d+\.\d+$/
  script:
    - UPDATE_VERSION_URL="${STAG_BE_URL?}/version/frontend/${CI_COMMIT_TAG?}"
    - curl -X POST  ${UPDATE_VERSION_URL?}
    - echo  ${UPDATE_VERSION_URL?}

add_version_prod:
  stage: add_version
  only:
    - /^v\d+\.\d+\.\d+$/
  script:
    - UPDATE_VERSION_URL="${PROD_BE_URL?}/version/frontend/${CI_COMMIT_TAG?}"
    - curl -X POST  ${UPDATE_VERSION_URL?}
    - echo  ${UPDATE_VERSION_URL?}
