
stages:
#  - test
  - deploy

#
#unit_test:
#  image: node:latest
#
#  stage: test
#  script:
#    - npm install
##    - npm test
#  artifacts:
#    paths:
#      - node_modules/

#Deploy for releasing to production
deploy_staging:
  stage: deploy
  tags:
    - runner2
  environment:
    name: staging
    url: https://stag.vomemo.com
  only:
  - staging
  before_script:
    - docker info
  script:
    - docker stop $(docker ps -a -q) || true
    - docker rm $(docker ps -a -q)  || true
    - docker build -t my-docker-image .
    - docker run -t -d -p 8080:8080  -e NODE_ENV=$STAG_ENV -e MONGO_STAG_URL=$MONGO_STAG_URL my-docker-image
deploy_production:
  stage: deploy
  tags:
    - runner1
  environment:
    name: production
    url: https://app.vomemo.com
  variables:
    NODE_ENV: $PROD_ENV
    MONGO_PROD_URL: $MONGO_PROD_URL

  only:
  - master
  before_script:
    - docker info
  script:
    - docker stop $(docker ps -a -q) || true
    - docker rm $(docker ps -a -q)  || true
    - docker build -t my-docker-image .
    - docker run -t -d -p 8080:8080  -e NODE_ENV=$PROD_ENV -e MONGO_PROD_URL=$MONGO_PROD_URL -e PROD_FIRE_BASE_CONFIG_SERVICE=$PROD_FIRE_BASE_CONFIG_SERVICE my-docker-image -e ES_HOST=$PROD_ES_HOST